export const ROUTES = {
    LANDING: "/",
    LOGIN: "/login",
    ONBOARDING: "/onboarding",
    DASHBOARD: "/dashboard",
    INSTITUTION: "/dashboard/institution",
    COURSES: "/dashboard/courses",
    COURSES_ADD: "/dashboard/courses/add",
    PROGRAMS: "/dashboard/programs",
    BATCHES: "/dashboard/batches",
    CENTERS: "/dashboard/centers",
    STUDENTS: "/dashboard/user/students",
    STUDENTS_ADD: "/dashboard/user/students/add",
    ADMINS: "/dashboard/user/admins",
    ADMINS_ADD: "/dashboard/user/admins/add",
    FACULTY: "/dashboard/faculty",
    RESULTS: "/dashboard/results",
    CUSTOMIZATION: "/dashboard/customization",
    MEDIA: "/dashboard/media",
    NOT_FOUND: "*",
} as const;
